version: "2"
services:
  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
            ithelp_application:
                ipv4_address: 172.28.0.4
    ports:
      - 3000:3000
networks:
    ithelp_application:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/24
                  gateway: 172.28.0.1
