version: "2"
services:
  pushgateway:
    image: prom/pushgateway:v0.4.0
    networks:
            ithelp_application:
                ipv4_address: 172.28.0.2
    ports:
      - 9091:9091
  prometheus:
    image: prom/prometheus:v2.18.1
    command: --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alerts/:/etc/prometheus/rules.d/
    networks:
            ithelp_application:
                ipv4_address: 172.28.0.3
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
            ithelp_application:
                ipv4_address: 172.28.0.4
    ports:
      - 3000:3000
  alertmanager:
    image: prom/alertmanager:v0.11.0
    command: --config.file=/etc/alertmanager/alertmanager.yml
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
            ithelp_application:
                ipv4_address: 172.28.0.5
                  
  # prometheus-pve-exporter:
  #   image: prompve/prometheus-pve-exporter
  #   networks:
  #           ithelp_application:
  #               ipv4_address: 172.28.0.6
  #   ports:
  #     - 9221:9221
  #   volumes:
  #     - ./prometheus-pve-exporter/pve.yml:/etc/pve.yml

networks:
    ithelp_application:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
                  gateway: 172.28.0.1
