version: '3'

services:
  mysql:
    image: mariadb
    container_name: librenms-db
    volumes:
      - ./mysql:/var/lib/mysql
      - ./50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf:ro
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=librenms
    restart: always

  librenms:
    build: .
    image: seti/librenms
    container_name: librenms
    hostname: librenms
    volumes:
      - ./data:/data
#     - /etc/timezone:/etc/timzone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8002:80
      - 514:514/tcp
      - 514:514/udp
    depends_on:
      - mysql
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mysql
      - DB_NAME=librenms
      - DB_USER=root
      - DB_PASS=password
      - TZ="Asia/Taipei"
      - POLLER=24
      - SERVICES_ENABLED=1
      - UPDATE_CHANNEL=master
